
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using at_solution.portal.primitive;

namespace at_solution.portal.entities
{
    public static class GetEntityHelper 
    {
        public static Article GetEntity(this ArticlePrimitive primitive)
        {
        		Article result = new Article(); 
        
        		result.Id = primitive.Id;
        		
        		result.User_Id = primitive.User_Id;
        		
        		result.Title = primitive.Title;
        		
        		result.Info = primitive.Info;
        		
        		result.FullText = primitive.FullText;
        		
        		result.CreateTime = primitive.CreateTime;
        		
        		result.DeleteTime = primitive.DeleteTime;
        		
        		result.Position = primitive.Position;
        		
        		return result;
        }
        
        public static ForumItem GetEntity(this ForumItemPrimitive primitive)
        {
        		ForumItem result = new ForumItem(); 
        
        		result.Id = primitive.Id;
        		
        		result.Article_Id = primitive.Article_Id;
        		
        		result.Text = primitive.Text;
        		
        		result.User_Id = primitive.User_Id;
        		
        		result.CreateTime = primitive.CreateTime;
        		
        		result.DeleteTime = primitive.DeleteTime;
        		
        		return result;
        }
        
        public static Role GetEntity(this RolePrimitive primitive)
        {
        		Role result = new Role(); 
        
        		result.Id = primitive.Id;
        		
        		result.Name = primitive.Name;
        		
        		result.CreateTime = primitive.CreateTime;
        		
        		result.DeleteTime = primitive.DeleteTime;
        		
        		return result;
        }
        
        public static Section GetEntity(this SectionPrimitive primitive)
        {
        		Section result = new Section(); 
        
        		result.Id = primitive.Id;
        		
        		result.Parent_Id = primitive.Parent_Id;
        		
        		result.Name = primitive.Name;
        		
        		result.Position = primitive.Position;
        		
        		result.CreateTime = primitive.CreateTime;
        		
        		result.DeleteTime = primitive.DeleteTime;
        		
        		return result;
        }
        
        public static User GetEntity(this UserPrimitive primitive)
        {
        		User result = new User(); 
        
        		result.Id = primitive.Id;
        		
        		result.Nick = primitive.Nick;
        		
        		result.Name = primitive.Name;
        		
        		result.Surname = primitive.Surname;
        		
        		result.Email = primitive.Email;
        		
        		result.Password = primitive.Password;
        		
        		result.PasswordSalz = primitive.PasswordSalz;
        		
        		result.Phone = primitive.Phone;
        		
        		result.CreateTime = primitive.CreateTime;
        		
        		result.DeleteTime = primitive.DeleteTime;
        		
        		return result;
        }
        
    }
}
