//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;


namespace at_solution.portal.primitive
{
    //[MetadataType(typeof(ForumItemMetaData))]
    public partial class ForumItemPrimitive : PrimitiveBase
    {
        #region Primitive Properties
    		public virtual Nullable<int> Article_Id
    		{
    			get;
    			set;
    		}
    		public string Text
    		{
            get;
            set;
    		}
    		public virtual Nullable<int> User_Id
    		{
    			get;
    			set;
    		}
    		public Nullable<System.DateTime> CreateTime
    		{
            get;
            set;
    		}
    		public Nullable<System.DateTime> DeleteTime
    		{
            get;
            set;
    		}

        #endregion
    }
    
}
