//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using at_solution.portal.primitive;

namespace at_solution.portal.entities
{
    public partial class ForumItem : ForumItemPrimitive
    {
        #region Primitive Properties
    		public override Nullable<int> Article_Id
    		{
            get { return _article_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_article_Id != value)
                    {
                        if (Article != null && Article.Id != value)
                        {
                            Article = null;
                        }
                        _article_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _article_Id;    
    
    		public override Nullable<int> User_Id
    		{
            get { return _user_Id; }
            set
            {        
                try
                {
                    _settingFK = true;
                    if (_user_Id != value)
                    {
                        if (User != null && User.Id != value)
                        {
                            User = null;
                        }
                        _user_Id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
    		}
    		private Nullable<int> _user_Id;    
    

        #endregion
        #region Navigation Properties
    
        public User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public Article Article
        {
            get { return _article; }
            set
            {
                if (!ReferenceEquals(_article, value))
                {
                    var previousValue = _article;
                    _article = value;
                    FixupArticle(previousValue);
                }
            }
        }
        private Article _article;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.ForumItems.Contains(this))
            {
                previousValue.ForumItems.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.ForumItems.Contains(this))
                {
                    User.ForumItems.Add(this);
                }
                if (User_Id != User.Id)
                {
                    User_Id = User.Id;
                }
            }
            else if (!_settingFK)
            {
                User_Id = null;
            }
        }
    
        private void FixupArticle(Article previousValue)
        {
            if (previousValue != null && previousValue.ForumItems.Contains(this))
            {
                previousValue.ForumItems.Remove(this);
            }
    
            if (Article != null)
            {
                if (!Article.ForumItems.Contains(this))
                {
                    Article.ForumItems.Add(this);
                }
                if (Article_Id != Article.Id)
                {
                    Article_Id = Article.Id;
                }
            }
            else if (!_settingFK)
            {
                Article_Id = null;
            }
        }

        #endregion
    }
}
