
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using at_solution.portal.primitive;

namespace at_solution.portal.entities
{
    public static class GetPrimitiveHelper 
    {
        public static ArticlePrimitive GetPrimitive(this Article entity)
        {
        		ArticlePrimitive primitive = new ArticlePrimitive(); 
        
        		primitive.Id = entity.Id;
        		
        		primitive.User_Id = entity.User_Id;
        		
        		primitive.Title = entity.Title;
        		
        		primitive.Info = entity.Info;
        		
        		primitive.FullText = entity.FullText;
        		
        		primitive.CreateTime = entity.CreateTime;
        		
        		primitive.DeleteTime = entity.DeleteTime;
        		
        		primitive.Position = entity.Position;
        		
        		return primitive;
        }
        
        public static ForumItemPrimitive GetPrimitive(this ForumItem entity)
        {
        		ForumItemPrimitive primitive = new ForumItemPrimitive(); 
        
        		primitive.Id = entity.Id;
        		
        		primitive.Article_Id = entity.Article_Id;
        		
        		primitive.Text = entity.Text;
        		
        		primitive.User_Id = entity.User_Id;
        		
        		primitive.CreateTime = entity.CreateTime;
        		
        		primitive.DeleteTime = entity.DeleteTime;
        		
        		return primitive;
        }
        
        public static RolePrimitive GetPrimitive(this Role entity)
        {
        		RolePrimitive primitive = new RolePrimitive(); 
        
        		primitive.Id = entity.Id;
        		
        		primitive.Name = entity.Name;
        		
        		primitive.CreateTime = entity.CreateTime;
        		
        		primitive.DeleteTime = entity.DeleteTime;
        		
        		return primitive;
        }
        
        public static SectionPrimitive GetPrimitive(this Section entity)
        {
        		SectionPrimitive primitive = new SectionPrimitive(); 
        
        		primitive.Id = entity.Id;
        		
        		primitive.Parent_Id = entity.Parent_Id;
        		
        		primitive.Name = entity.Name;
        		
        		primitive.Position = entity.Position;
        		
        		primitive.CreateTime = entity.CreateTime;
        		
        		primitive.DeleteTime = entity.DeleteTime;
        		
        		return primitive;
        }
        
        public static UserPrimitive GetPrimitive(this User entity)
        {
        		UserPrimitive primitive = new UserPrimitive(); 
        
        		primitive.Id = entity.Id;
        		
        		primitive.Nick = entity.Nick;
        		
        		primitive.Name = entity.Name;
        		
        		primitive.Surname = entity.Surname;
        		
        		primitive.Email = entity.Email;
        		
        		primitive.Password = entity.Password;
        		
        		primitive.PasswordSalz = entity.PasswordSalz;
        		
        		primitive.Phone = entity.Phone;
        		
        		primitive.CreateTime = entity.CreateTime;
        		
        		primitive.DeleteTime = entity.DeleteTime;
        		
        		return primitive;
        }
        
    }
}
