//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using at_solution.portal.primitive;

namespace at_solution.portal.entities
{
    public partial class User : UserPrimitive
    {
        #region Navigation Properties
    
        public ICollection<ForumItem> ForumItems
        {
            get
            {
                if (_forumItems == null)
                {
                    var newCollection = new FixupCollection<ForumItem>();
                    newCollection.CollectionChanged += FixupForumItems;
                    _forumItems = newCollection;
                }
                return _forumItems;
            }
            set
            {
                if (!ReferenceEquals(_forumItems, value))
                {
                    var previousValue = _forumItems as FixupCollection<ForumItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupForumItems;
                    }
                    _forumItems = value;
                    var newValue = value as FixupCollection<ForumItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupForumItems;
                    }
                }
            }
        }
        private ICollection<ForumItem> _forumItems;
    
        public ICollection<Role> Roles
        {
            get
            {
                if (_roles == null)
                {
                    var newCollection = new FixupCollection<Role>();
                    newCollection.CollectionChanged += FixupRoles;
                    _roles = newCollection;
                }
                return _roles;
            }
            set
            {
                if (!ReferenceEquals(_roles, value))
                {
                    var previousValue = _roles as FixupCollection<Role>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRoles;
                    }
                    _roles = value;
                    var newValue = value as FixupCollection<Role>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRoles;
                    }
                }
            }
        }
        private ICollection<Role> _roles;
    
        public ICollection<Article> Articles
        {
            get
            {
                if (_articles == null)
                {
                    var newCollection = new FixupCollection<Article>();
                    newCollection.CollectionChanged += FixupArticles;
                    _articles = newCollection;
                }
                return _articles;
            }
            set
            {
                if (!ReferenceEquals(_articles, value))
                {
                    var previousValue = _articles as FixupCollection<Article>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupArticles;
                    }
                    _articles = value;
                    var newValue = value as FixupCollection<Article>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupArticles;
                    }
                }
            }
        }
        private ICollection<Article> _articles;

        #endregion
        #region Association Fixup
    
        private void FixupForumItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ForumItem item in e.NewItems)
                {
                    item.User = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ForumItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.User, this))
                    {
                        item.User = null;
                    }
                }
            }
        }
    
        private void FixupRoles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Role item in e.NewItems)
                {
                    if (!item.Users.Contains(this))
                    {
                        item.Users.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Role item in e.OldItems)
                {
                    if (item.Users.Contains(this))
                    {
                        item.Users.Remove(this);
                    }
                }
            }
        }
    
        private void FixupArticles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Article item in e.NewItems)
                {
                    item.User = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Article item in e.OldItems)
                {
                    if (ReferenceEquals(item.User, this))
                    {
                        item.User = null;
                    }
                }
            }
        }

        #endregion
    }
}
